## API Deployment
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dirt-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dirt-api
  template:
    metadata:
      labels:
        app: dirt-api
    spec:
      containers:
        - name: dirt-api
          image: ghcr.io/fehho/dirt-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: "1Gi"
              cpu: "500m"
          env:
            - name: DIRT_DB_CONSTRING
              valueFrom:
                configMapKeyRef:
                  name: dirt-api
                  key: db-constring
            - name: DIRT_DB_USER
              valueFrom:
                configMapKeyRef:
                  name: dirt-api
                  key: db-user
            - name: DIRT_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dirt-db
                  key: mssql-sa-password
---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  type: ClusterIP
  selector:
    app: dirt-api
  ports:
    - port: 3000
      targetPort: 3000
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: dirt-api
data:
  db-constring: "dbi:ODBC:Driver=ODBC Driver 18 for SQL Server;Database=MyDirtDB;Server=dirt-db,1433;TrustServerCertificate=yes"
  db-user: "sa"
