apiVersion: apps/v1
kind: Deployment
metadata:
  name: dirt-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dirt-api
  template:
    metadata:
      labels:
        app: dirt-api
    spec:
      containers:
        - name: dirt-api
          env:
            - name: DIRT_DB_CONSTRING
              valueFrom:
                configMapKeyRef:
                  name: dirt-api-config
                  key: db-constring
            - name: DIRT_DB_USER
              valueFrom:
                configMapKeyRef:
                  name: dirt-api-config
                  key: db-user
            - name: DIRT_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dirt-db-secrets
                  key: mssql-sa-password
          image: ghcr.io/fehho/dirt-api:latest@sha256:d1d5d6eeeb230a25a338aaade5ff8725cf73778a595df9dc40b9fd1a80557f3e
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: "1Gi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  type: ClusterIP
  selector:
    app: dirt-api
  ports:
    - port: 3000
      targetPort: 3000
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: dirt-api-config
data:
  db-constring: "dbi:ODBC:Driver=ODBC Driver 18 for SQL Server;Database=MyDirtDB;Server=dirt-db,1433;TrustServerCertificate=yes"
  db-user: "sa"
