apiVersion: apps/v1
kind: Deployment
metadata:
  name: dirt-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dirt-app
  template:
    metadata:
      labels:
        app: dirt-app
    spec:
      containers:
        - name: dirt-app
          env:
            - name: DIRT_APP_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  name: dirt-app-config
                  key: hostname
          image: ghcr.io/fehho/dirt-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  type: ClusterIP
  selector:
    app: dirt-app
  ports:
    - port: 3000
      targetPort: 3000
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dirt-app-config
data:
  hostname: dirt.af.mil
