apiVersion: apps/v1
kind: Deployment
metadata:
  name: dirt-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dirt-app
  template:
    metadata:
      labels:
        app: dirt-app
    spec:
      containers:
        - name: dirt-app
          image: ghcr.io/fehho/dirt-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  type: ClusterIP
  selector:
    app: dirt-app
  ports:
    - port: 3000
      targetPort: 3000
