## Application Deployment
#
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dirt-db
spec:
  selector:
    matchLabels:
      app: dirt-db
  serviceName: dirt-db
  replicas: 1
  template:
    metadata:
      labels:
        app: dirt-db
    spec:
      volumes:
        - name: dirt-db-files
          configMap:
            name: dirt-db-files
      containers:
        - name: dirt-db
          image: ghcr.io/elblayko/dirt-db:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 1433
              name: dirt-db
          volumeMounts:
            - name: db-data
              mountPath: /var/opt/mssql/data
            - name: dirt-db-files
              mountPath: /var/opt/mssql/schema
          env:
            - name: MSSQL_SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dirt-db
                  key: mssql-sa-password
            - name: ACCEPT_EULA
              valueFrom:
                configMapKeyRef:
                  name: dirt-db
                  key: accept-eula
  volumeClaimTemplates:
    - metadata:
        name: db-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
---
## ClusterIP Service
#
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  type: ClusterIP
  selector:
    app: dirt-db
  ports:
    - port: 1433
      targetPort: 1433
---
## Secret Configuration
#
apiVersion: v1
kind: Secret
metadata:
  name: dirt-db
type: Opaque
data:
  mssql-sa-password: eW91clN0cm9uZyghKVBhc3N3b3Jk # echo -n 'yourStrong(!)Password' | base64
---
## Application Configuration
#
apiVersion: v1
kind: ConfigMap
metadata:
  name: dirt-db
data:
  accept-eula: "Y"
