apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dirt-db
spec:
  selector:
    matchLabels:
      app: dirt-db
  serviceName: dirt-db
  replicas: 1
  template:
    metadata:
      labels:
        app: dirt-db
    spec:
      containers:
        - name: dirt-db
          env:
            - name: MSSQL_SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dirt-db-secrets
                  key: mssql-sa-password
            - name: ACCEPT_EULA
              valueFrom:
                configMapKeyRef:
                  name: dirt-db-config
                  key: accept-eula
          image: ghcr.io/elblayko/dirt-db:latest@sha256:6ae3c67e471e7a881fe82ce50957eb3d0c756f8c4412e314263651ba105d8782
          imagePullPolicy: IfNotPresent
          ports:
            - name: dirt-db
              containerPort: 1433
          volumeMounts:
            - name: db-data
              mountPath: /var/opt/mssql/data
            - name: dirt-db-config
              mountPath: /var/opt/mssql/schema
      volumes:
        - name: dirt-db-config
          configMap:
            name: dirt-db-config
            items:
              - key: schema
                path: schema.sql
  volumeClaimTemplates:
    - metadata:
        name: db-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  type: ClusterIP
  selector:
    app: dirt-db
  ports:
    - port: 1433
      targetPort: 1433
---
apiVersion: v1
kind: Secret
metadata:
  name: dirt-db-secrets
type: Opaque
data:
  mssql-sa-password: UGFzc3cwcmQ/ # echo -n 'Passw0rd?' | base64
