name: CI
on:
  - push
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Start Minikube
        uses: medyagh/setup-minikube@latest

      - name: Run a command
        run: curl -sfL https://raw.githubusercontent.com/elblayko/dirt-kube/master/minikube-deploy.sh | bash -s - --with-dummy-data --no-start-minikube
        shell: bash